name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Build gem
        run: gem build en14960.gemspec

      - name: Configure RubyGems credentials
        uses: rubygems/configure-rubygems-credentials@main

      - name: Publish to RubyGems
        run: gem push *.gem

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.gem'
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}